spring.application.name=Trazabilidad
server.port=8083

# DynamoDB
aws.dynamodb.endpoint=${DYNAMODB_ENDPOINT:http://localhost:8000}
aws.dynamodb.region=${AWS_REGION:us-east-1}
aws.dynamodb.access-key=${AWS_ACCESS_KEY:local}
aws.dynamodb.secret-key=${AWS_SECRET_KEY:local}
aws.dynamodb.table-name=trazabilidad
